import { Product, MoodCollection } from './types';

export const MOOD_COLLECTIONS: MoodCollection[] = [
  {
    id: 'wedding',
    title: 'The Solah Shringar Bridal Atelier',
    subtitle: 'Golden Brocades & Sacred Silk Drapes',
    editorialWallText: 'Woven for sacred unions and imperial celebrations, each piece in this atelier incorporates pure gold zari wires intertwined with Mulberry silk.',
    moodKey: 'wedding',
    heroImage: '/assets/article-a/1.jpg',
    accentColorHex: '#D9A6A0',
  },
  {
    id: 'royal',
    title: 'Imperial Durbar Heritage',
    subtitle: 'Midnight Indigo & Courtly Velvet Weaves',
    editorialWallText: 'Drawing directly from royal archives of Awadh and Mysore, these weaves evoke the dignified silence of royal courts.',
    moodKey: 'royal',
    heroImage: '/assets/article-f/1.jpg',
    accentColorHex: '#1B2A4A',
  },
  {
    id: 'heirloom-gift',
    title: 'Heirloom & Dynasty Treasures',
    subtitle: 'Timeless Oxblood & Pure Mulberry Silks',
    editorialWallText: 'Crafted as physical heirlooms to be passed across three generations. Dyed with madder root and pomegranate rind.',
    moodKey: 'heirloom-gift',
    heroImage: '/assets/article-c/1.jpg',
    accentColorHex: '#6B1E28',
  },
  {
    id: 'quiet-luxury',
    title: 'The Minimalist Loom',
    subtitle: 'Raw Pashmina, Tussar & Undyed Linen',
    editorialWallText: 'Understated elegance celebrating the tactile texture of raw handspun fibers. Pure, unpretentious luxury woven without chemical treatment.',
    moodKey: 'quiet-luxury',
    heroImage: '/assets/article-d/1.jpg',
    accentColorHex: '#D8CCB8',
  },
  {
    id: 'sustainable-luxe',
    title: 'Eri Silk & Botanical Dyes',
    subtitle: 'Ahimsa Peace Silk from Assam Valleys',
    editorialWallText: 'Cruelty-free Eri silk harvested naturally after the silkworm emerges, dyed exclusively with marigold petals, indigo leaf, and walnut husks.',
    moodKey: 'sustainable-luxe',
    heroImage: '/assets/article-[#E8D8A8]/1.jpg',
    accentColorHex: '#5C6B4F',
  },
  {
    id: 'temple-heritage',
    title: 'Sacred Temple Drapes',
    subtitle: 'Kanchipuram Temple Borders & Sacred Geometry',
    editorialWallText: 'Inspired by the carved stone pillars of South Indian temple architecture. Features korvai joinery technique.',
    moodKey: 'temple-heritage',
    heroImage: '/assets/article-e/1.jpg',
    accentColorHex: '#0B3D2E',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    slug: 'pochampally-ikat-silk-saree',
    title: 'Pochampally Double-Ikat Silk Saree — Peacock Motif',
    weaveName: 'Double-Ikat Resist Dye Silk',
    region: 'Pochampally, Telangana',
    weaverId: 'radha-devi',
    weaverName: 'Radha Devi',
    weaverVillage: 'Pochampally',
    weaverAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    price: 18500,
    weaverSharePercentage: 82,
    stock: 3,
    mood: 'royal',
    material: 'Pure Mulberry Silk & Botanical Organic Dyes',
    hoursInvested: 140,
    giCertified: true,
    description: 'Authentic Pochampally double-Ikat handloom drape. Thread is hand-dyed before weaving on traditional wooden pit looms.',
    culturalMeaning: 'The double-peacock motif represents grace, fidelity, and royal protection across Telangana heritage households.',
    textureUrl: '/assets/article-a/1.jpg',
    macroTextureUrl: '/assets/article-a/2.jpg',
    images: [
      '/assets/article-a/1.jpg',
      '/assets/article-a/2.jpg',
      '/assets/article-a/3.jpg',
      '/assets/article-a/4.jpg',
    ],
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    qrId: 'PASSPORT-PC-2026-8841',
  },
  {
    id: 'p2',
    slug: 'kanjeevaram-temple-border-saree',
    title: 'Kanjeevaram Korvai Temple Border Silk Saree — Crimson Gold',
    weaveName: 'Korvai Interlocked Border Mulberry Silk',
    region: 'Kanchipuram, Tamil Nadu',
    weaverId: 'lakshmi-amma',
    weaverName: 'Lakshmi Amma',
    weaverVillage: 'Kanchipuram',
    weaverAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    price: 32000,
    weaverSharePercentage: 84,
    stock: 2,
    mood: 'wedding',
    material: 'Heavyweight Mulberry Silk & Pure Silver Zari',
    hoursInvested: 210,
    giCertified: true,
    description: 'Woven with three single threads of silk twisted together with silver zari wire.',
    culturalMeaning: 'The temple gopuram border mirrors the grand granite gateway arches of Ekambareswarar Temple.',
    textureUrl: '/assets/article-b/1.jpg',
    macroTextureUrl: '/assets/article-b/1.jpg',
    images: [
      '/assets/article-b/1.jpg',
    ],
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    qrId: 'PASSPORT-TN-2026-9031',
  },
  {
    id: 'p3',
    slug: 'assam-muga-silk-gamosa',
    title: 'Assam Wild Golden Muga Silk Dupatta',
    weaveName: 'Wild Golden Muga Jacquard',
    region: 'Sualkuchi, Assam',
    weaverId: 'bipul-das',
    weaverName: 'Bipul Das',
    weaverVillage: 'Sualkuchi',
    weaverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    price: 4200,
    weaverSharePercentage: 85,
    stock: 6,
    mood: 'sustainable-luxe',
    material: '100% Wild Muga Silk (Assam endemic)',
    hoursInvested: 45,
    giCertified: true,
    description: 'Muga silk is the rarest wild silk on earth, naturally golden and gaining rich luster with every wash.',
    culturalMeaning: 'A sacred symbol of honor and respect offered during Bihu celebrations along the Brahmaputra.',
    textureUrl: '/assets/article-c/1.jpg',
    macroTextureUrl: '/assets/article-c/2.jpg',
    images: [
      '/assets/article-c/1.jpg',
      '/assets/article-c/2.jpg',
      '/assets/article-c/3.jpg',
    ],
    qrId: 'PASSPORT-AS-2026-1102',
  },
  {
    id: 'p4',
    slug: 'kashmir-pashmina-shawl',
    title: 'Fine Handspun Kashmir Kani Needle Pashmina Stole',
    weaveName: 'Kani Needle Weave Pashmina',
    region: 'Srinagar, Kashmir',
    weaverId: 'ghulam-nabi',
    weaverName: 'Ghulam Nabi',
    weaverVillage: 'Srinagar',
    weaverAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    price: 27000,
    weaverSharePercentage: 80,
    stock: 2,
    mood: 'quiet-luxury',
    material: '100% Raw Ladakh Changthangi Pashmina',
    hoursInvested: 180,
    giCertified: true,
    description: 'Combed by hand from Changthangi goats at 14,000 feet. Woven on wooden Kani sticks by master Kashmiri craftsmen.',
    culturalMeaning: 'The traditional Chinar leaf border captures the autumn foliage of Dal Lake gardens.',
    textureUrl: '/assets/article-d/1.jpg',
    macroTextureUrl: '/assets/article-d/2.jpg',
    images: [
      '/assets/article-d/1.jpg',
      '/assets/article-d/2.jpg',
    ],
    qrId: 'PASSPORT-JK-2026-4410',
  },
  {
    id: 'p5',
    slug: 'banarasi-kadwa-shikargah',
    title: 'Imperial Banarasi Kadwa Real Zari Brocade',
    weaveName: 'Varanasi Kadwa Hand-Brocade',
    region: 'Varanasi, Uttar Pradesh',
    weaverId: 'gurudev-varma',
    weaverName: 'Gurudev Varma',
    weaverVillage: 'Varanasi Old Quarter',
    weaverAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    price: 245000,
    weaverSharePercentage: 85,
    stock: 2,
    mood: 'heirloom-gift',
    material: 'Pure Katan Silk & 24K Real Gold Zari',
    hoursInvested: 310,
    giCertified: true,
    description: 'Depicting royal hunting reserves woven using the Kadwa pit loom technique where each motif is hand-drawn separately.',
    culturalMeaning: 'Homage to Awadh court textiles, celebrating flora, fauna, and imperial dignity.',
    textureUrl: '/assets/article-e/1.jpg',
    macroTextureUrl: '/assets/article-e/2.jpg',
    images: [
      '/assets/article-e/1.jpg',
      '/assets/article-e/2.jpg',
      '/assets/article-e/3.jpg',
    ],
    qrId: 'PASSPORT-UP-2026-0412',
  },
  {
    id: 'p6',
    slug: 'paithani-royal-peacock-saree',
    title: 'Royal Yeola Paithani Silk Saree — Peacock Pallu',
    weaveName: 'Tapestry Weave Gold Pallu',
    region: 'Yeola, Maharashtra',
    weaverId: 'savita-kshirsagar',
    weaverName: 'Savita Kshirsagar',
    weaverVillage: 'Yeola',
    weaverAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    price: 68000,
    weaverSharePercentage: 83,
    stock: 3,
    mood: 'wedding',
    material: 'Handspun Silk & Real Gold Testing Wire',
    hoursInvested: 165,
    giCertified: true,
    description: 'Characterized by borders of oblique square design and a pallu with a peacock motif woven with zero reverse threads.',
    culturalMeaning: 'Considered the queen of Maharashtrian heritage textiles, symbolising marital bliss and prosperity.',
    textureUrl: '/assets/article-f/1.jpg',
    macroTextureUrl: '/assets/article-f/2.jpg',
    images: [
      '/assets/article-f/1.jpg',
      '/assets/article-f/2.jpg',
      '/assets/article-f/3.jpg',
      '/assets/article-f/4.jpg',
      '/assets/article-f/5.jpg',
    ],
    qrId: 'PASSPORT-MH-2026-7721',
  },
];

export async function getFeaturedProducts(): Promise<Product[]> {
  await new Promise((res) => setTimeout(res, 200));
  return MOCK_PRODUCTS;
}

export async function getMoodCollectionPreviews(): Promise<MoodCollection[]> {
  await new Promise((res) => setTimeout(res, 150));
  return MOOD_COLLECTIONS;
}

export async function getProductsByMood(mood: string): Promise<Product[]> {
  await new Promise((res) => setTimeout(res, 200));
  if (!mood || mood === 'all') return MOCK_PRODUCTS;
  return MOCK_PRODUCTS.filter((p) => p.mood === mood);
}

export async function getProductBySlug(slug: string): Promise<Product | undefined> {
  await new Promise((res) => setTimeout(res, 150));
  return MOCK_PRODUCTS.find((p) => p.slug === slug) || MOCK_PRODUCTS[0];
}
